version: '2.1'

services:
  eureka-sv:
    build: eureka-sv
    mem_limit: 512m
    ports:
      - "8761:8761"
    networks:
      - 'sistemamercadocompras-network'
  ventas-service:
    build: ventas-service
    mem_limit: 512m
    ports:
      - "8083:8083"
    networks:
      - 'sistemamercadocompras-network'
  carrito-service:
    build: carrito-service
    mem_limit: 512m
    ports:
      - "8082:8082"
    networks:
      - 'sistemamercadocompras-network'
  productos-service:
    build: productos-service
    mem_limit: 512m
    ports:
      - "8081:8081"
    networks:
      - 'sistemamercadocompras-network'
  api-gateway:
    build: api-gateway
    mem_limit: 512m
    ports:
      - "443:443"
    networks:
      - 'sistemamercadocompras-network'
networks:
  sistemamercadocompras-network: